# /// script
# requires-python = ">=3.9"
# ///
"""deckpack.py — stamp a Stream Deck button pack for Muninn.

The recorder bot exposes a loopback control surface (see the recorder
module's `control.py`): 127.0.0.1 endpoints that start/stop recording
and report status. This generator stamps the owner-facing half — a
folder of tiny scripts that curl those endpoints, bindable to Stream
Deck keys via its built-in System ▸ Open action, plus an experimental
`.streamDeckProfile` and a README with exact install steps.

Two robustness tiers, by design:
  1. The scripts (`.command` on macOS, `.cmd` on Windows) are the
     reliable path — a Stream Deck key set to System ▸ Open pointing at
     one of these runs it, no plugins. They are plain curl; they work
     from a double-click or any launcher too.
  2. The `.streamDeckProfile` is a best-effort convenience: a zip of a
     manifest mapping keys to those scripts. Profile schemas drift
     between Stream Deck versions, so it is offered as a starting point,
     with the manual bind documented as the guaranteed route.

The pack stamps exactly the four control-surface keys: Start Recording,
Stop Recording, Status, Help. These map 1:1 to the recorder control
surface; the pack drives nothing else.

Pure text/bytes builders (control_script, readme_text, profile_bytes,
pack_plan) do no I/O and golden-test on any OS; build_pack writes them.

Usage:
    uv run deckpack.py [--campaign DIR] [--dest DIR]
        [--base-url URL] [--token SECRET] [--port N]
        [--target macos|windows|both] [--name LABEL]
"""

import argparse
import io
import json
import platform
import re
import shlex
import zipfile
from pathlib import Path


def _sh_quote(value):
    """POSIX-shell-quote a value baked into a bash script. Single-quoting
    (what shlex.quote does) neutralizes every shell metacharacter — `"`,
    backtick, `$`, whitespace — so a crafted --base-url/--token can't break
    out of the assignment or inject a command."""
    return shlex.quote(value)


def _cmd_quote(value):
    """Escape a value for a Windows batch `set VAR=...` (unquoted) context.
    Double the `%` metachar and caret-escape the cmd shell metacharacters so
    a crafted --base-url/--token can't inject. The scripts reference the value
    only through `%VAR%` expansions inside double quotes thereafter, so the
    escaped-at-assignment form is what runs."""
    value = value.replace("%", "%%")
    out = []
    for ch in value:
        if ch in '^&<>|"':
            out.append("^")
        out.append(ch)
    return "".join(out)

# The four core keys: label -> (method, endpoint). These map 1:1 to the
# recorder control surface, which maps 1:1 to /record start|stop|status.
CORE = [
    ("Start Recording", "POST", "/record/start"),
    ("Stop Recording", "POST", "/record/stop"),
    ("Recording Status", "GET", "/status"),
    ("Muninn Help", "GET", "/healthz"),
]


def slug(label):
    return re.sub(r"[^a-z0-9]+", "-", label.lower()).strip("-")


def _bash_header(title):
    return (f"#!/bin/bash\n"
            f"# Muninn Stream Deck button — {title}\n"
            f"# Generated by eddic streamdeck/deckpack. LOCAL ONLY:\n"
            f"# it may carry your control token — keep it out of git.\n")


def control_script(label, method, endpoint, base_url, token, target):
    """A curl-the-control-surface script. Returns (filename, text)."""
    if target == "windows":
        # base_url/token are baked via `set VAR=...` and referenced only as
        # %BASE% / %TOKEN% thereafter, so escaping is confined to the
        # assignment (see _cmd_quote). The auth header points at %TOKEN%.
        body = [
            "@echo off",
            f"REM Muninn Stream Deck button - {label}",
            f"set BASE={_cmd_quote(base_url)}",
        ]
        if token:
            body.append(f"set TOKEN={_cmd_quote(token)}")
        auth = ' -H "X-Muninn-Token: %TOKEN%"' if token else ""
        body += [
            f"echo Muninn - {label}...",
            (f'curl -sS -X {method} "%BASE%{endpoint}"{auth}'),
            "echo.",
            "timeout /t 2 >nul",
        ]
        return f"{slug(label)}.cmd", "\r\n".join(body) + "\r\n"
    # macOS / posix: bash with an optional auth header array, JSON
    # pretty-printed when python3 is present. base_url/token are single-
    # quoted so no metacharacter in them can break out or inject.
    lines = [_bash_header(label),
             f'BASE={_sh_quote(base_url)}',
             f'TOKEN={_sh_quote(token)}',
             "AUTH=()",
             '[ -n "$TOKEN" ] && AUTH=(-H "X-Muninn-Token: $TOKEN")',
             f'echo "🎙️  Muninn — {label}"',
             (f'curl -sS "${{AUTH[@]}}" -X {method} "$BASE{endpoint}" '
              f'| (python3 -m json.tool 2>/dev/null || cat)'),
             "echo",
             "sleep 1"]
    return f"{slug(label)}.command", "\n".join(lines) + "\n"


def profile_bytes(name, buttons):
    """Best-effort `.streamDeckProfile` (a zip of manifest.json) mapping
    keys to System ▸ Open on each script. `buttons` is a list of
    (title, absolute_script_path). Schema follows the documented Stream
    Deck profile shape; validity across app versions is not guaranteed,
    so the README treats manual binding as the reliable path."""
    actions = {}
    for i, (title, path) in enumerate(buttons):
        col, row = i % 5, i // 5           # standard 5x3 deck
        actions[f"{col},{row}"] = {
            "Name": "Open",
            "UUID": "com.elgato.streamdeck.system.open",
            "State": 0,
            "Settings": {"path": str(path), "openInBrowser": False},
            "States": [{
                "Title": title.replace(" ", "\n"),
                "TitleShow": True,
                "FontSize": "9",
            }],
        }
    manifest = {
        "Name": name,
        "Version": "1.0",
        "Actions": actions,
        "DeviceModel": "20GAA9901",   # Stream Deck MK.2 (15 keys)
        "DeviceUUID": "",
    }
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as z:
        z.writestr(f"{name}.sdProfile/manifest.json",
                   json.dumps(manifest, indent=2))
    return buf.getvalue()


def readme_text(name, base_url, has_token, target):
    """Install and bind instructions for the owner."""
    ext = ".command" if target != "windows" else ".cmd"
    tok = ("This pack carries your control token in each script — it is "
           "local-only, so keep the folder out of git.\n"
           if has_token else
           "The recorder's control surface has no token set, so these "
           "scripts send none. If you set CONTROL_TOKEN later, "
           "regenerate the pack.\n")
    lines = [
        f"# {name} — Stream Deck pack for Muninn",
        "",
        "These buttons drive the recorder bot's local control surface "
        f"at `{base_url}` — the same start / stop / status actions as the "
        "`/record` slash commands, from a Stream Deck key.",
        "",
        "## Prerequisite",
        "",
        "The recorder must be running (double-click the Muninn launcher, "
        "or `eddic run recorder`). Its control surface is on by default; "
        "it is bound to `127.0.0.1` and never leaves this machine. "
        + tok,
        "## Bind the buttons (reliable path)",
        "",
        "For each key you want, in the Stream Deck app:",
        "",
        "1. Drag **System ▸ Open** onto the key.",
        f"2. Set **App / File** to the matching script in this folder "
        f"(e.g. `start-recording{ext}`).",
        "3. Set the key **Title** (Start, Stop, Status, …).",
        "",
        f"On macOS the scripts are `{ext}` files; make them executable "
        "once with `chmod +x *.command` (the generator already does "
        "this) and, on first run, approve the Terminal-open prompt. "
        "On Windows they are `.cmd` files and need `curl`, which ships "
        "with Windows 10+.",
        "",
        "## Buttons",
        "",
        f"- **Start Recording** → `POST {base_url}/record/start`",
        f"- **Stop Recording** → `POST {base_url}/record/stop`",
        f"- **Recording Status** → `GET {base_url}/status`",
        f"- **Muninn Help** → `GET {base_url}/healthz` (is the bot up?)",
        "",
        "## The .streamDeckProfile (experimental)",
        "",
        f"`{slug(name)}.streamDeckProfile` is a pre-built profile you can "
        "double-click to import as a starting point. Stream Deck profile "
        "formats drift between app versions, so if the import is rejected "
        "or a key looks wrong, fall back to the manual bind above — it "
        "always works.",
        "",
    ]
    return "\n".join(lines)


def pack_plan(name, base_url, token, target):
    """Pure plan of the pack: list of (relpath, kind, content) where kind
    is 'script'|'text'|'profile'. Bytes for the profile, str otherwise.
    Deterministic; the golden test asserts against this."""
    files = []
    button_paths = []                       # (title, script filename)
    for label, method, endpoint in CORE:
        fn, text = control_script(label, method, endpoint, base_url,
                                  token, target)
        files.append((fn, "script", text))
        button_paths.append((label, fn))
    files.append(("README.md", "text",
                  readme_text(name, base_url, bool(token), target)))
    # profile references absolute script paths; the writer resolves them
    files.append((f"{slug(name)}.streamDeckProfile", "profile",
                  button_paths))
    return files


def build_pack(dest, name, base_url, token, target):
    """Materialize the pack under `dest`. Returns the list of written
    paths. `target` 'both' stamps macOS and Windows scripts side by
    side."""
    dest = Path(dest)
    dest.mkdir(parents=True, exist_ok=True)
    targets = ["macos", "windows"] if target == "both" else [target]
    written = []
    button_paths = []
    for tgt in targets:
        plan = pack_plan(name, base_url, token, tgt)
        for relpath, kind, content in plan:
            out = dest / relpath
            out.parent.mkdir(parents=True, exist_ok=True)
            if kind == "profile":
                if tgt != targets[0]:
                    continue               # one profile, first target
                button_paths = [(t, str((dest / fn).resolve()))
                                for t, fn in content]
                out.write_bytes(profile_bytes(name, button_paths))
            elif kind == "script":
                nl = "" if tgt == "windows" else "\n"
                with open(out, "w", encoding="utf-8", newline=nl) as fh:
                    fh.write(content)
                if tgt != "windows":
                    out.chmod(0o755)
            else:
                out.write_text(content, encoding="utf-8")
            written.append(out)
    return written


def main(argv=None):
    ap = argparse.ArgumentParser(description="Stamp a Muninn Stream Deck "
                                             "button pack.")
    ap.add_argument("--campaign", help="campaign directory (default: cwd)")
    ap.add_argument("--dest", help="output dir (default: "
                    "<campaign>/streamdeck)")
    ap.add_argument("--base-url", default=None,
                    help="control surface base URL "
                    "(default http://127.0.0.1:<port>)")
    ap.add_argument("--port", type=int, default=8776,
                    help="control surface port (default 8776)")
    ap.add_argument("--token", default="",
                    help="control shared secret (must match "
                    "CONTROL_TOKEN); omit if none")
    ap.add_argument("--target", default="auto",
                    choices=["macos", "windows", "both", "auto"],
                    help="which scripts to stamp (default: this OS)")
    ap.add_argument("--name", default="Muninn",
                    help="pack/profile name (default: Muninn)")
    args = ap.parse_args(argv)

    campaign = (Path(args.campaign).expanduser().resolve()
                if args.campaign else Path.cwd())
    dest = (Path(args.dest).expanduser().resolve() if args.dest
            else campaign / "streamdeck")
    base_url = args.base_url or f"http://127.0.0.1:{args.port}"
    target = args.target
    if target == "auto":
        target = "windows" if platform.system() == "Windows" else "macos"

    written = build_pack(dest, args.name, base_url, args.token, target)
    print(f"stamped {len(written)} file(s) under {dest}:")
    for p in written:
        print(f"  {p.name}")
    print("Bind each script to a Stream Deck key via System ▸ Open; "
          "see README.md.")
    return 0


if __name__ == "__main__":
    import sys
    sys.exit(main())
